// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm6RtrP2NgzU-_t6fM8vMSlJak7onRE38',
    appId: '1:775693534440:web:db7e3ace5d7918c007355d',
    messagingSenderId: '775693534440',
    projectId: 'quiz-app-77cde',
    authDomain: 'quiz-app-77cde.firebaseapp.com',
    storageBucket: 'quiz-app-77cde.appspot.com',
    measurementId: 'G-V00JD4HE23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeApYubXglKm3NcQbRYgbwutpNOyCnNQs',
    appId: '1:775693534440:android:4f33f87b30cab88b07355d',
    messagingSenderId: '775693534440',
    projectId: 'quiz-app-77cde',
    storageBucket: 'quiz-app-77cde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkxasJo7kgXJZE1kH6sKC3GLXKkA0129A',
    appId: '1:775693534440:ios:4f5b3584a6704fc407355d',
    messagingSenderId: '775693534440',
    projectId: 'quiz-app-77cde',
    storageBucket: 'quiz-app-77cde.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );
}
